package users;

import comments.Comment;
import exceptions.*;
import posts.Post;

import java.util.Iterator;
import java.util.List;

/**
 * The User interface, holding several method used by all kinds of users.
 *
 * @author Luis Tripa 57882
 * @author Raquel Melo 57706
 */
public interface User {

	/**
	 * Getter method for the ID of the user.
     *
	 * @return The user ID
	 */
    String getID();

    /**
	 * Getter method for the kind of the user.
     *
	 * @return The user kind
	 */
    UserKind getUserKind();

    /**
	 * Getter method for the number of friends of the user.
     *
	 * @return the number of friends.
	 */
    int getFriendCount();

    /**
	 * Getter method for the number of posts made by the user.
     *
	 * @return the number of posts made.
	 */
    Integer getPostsCount();

    /**
   	 * Getter method for the number of comments made by the user.
     *
   	 * @return the number of comments.
   	 */
    int getCommentsCount();

    /**
     * Method that generates an ID for a new post. The post ID is generated by incrementing the variable postIDCounter
     *
     * @return The generated post ID
     */
    int getPostIDCounter();

    /**
     * Getter method for the number of read posts of the user.
     *
     * @return The number of read posts
     */
    int getReadPostNumber();
    
    /**
     * Getter method for the number of posts that can be accessed by the user (sums the number of posts made with the number of posts received).
     *
     * @return number of accessible posts.
     */
    Integer getTotalAccessiblePosts();

    /**
     * Getter method for the responsiveness (relation between the number of posts read and the number of accessible posts.
     *
     * @return The user's responsiveness percentage
     */
    Double getResponsiveness();
    
    /**
     * Getter method for the number of lies made by this user.
     *
     * @return The number of lies
     */
	Integer getNumberOfLies();

    /**
     * Method that sets a friendship between the user and another user.
     *
     * @param user which is going to become friends with the current user.
     * @throws UsersAreAlreadyFriendsException if both users are already friends
     */
    void addFriend(User user) throws UsersAreAlreadyFriendsException;

    /**
     * Creates a new iterator of users, but only of the friends of this user.
     *
     * @return An iterator of users
     * @throws UserHasNoFriendsException if the user has no friends
     */
    Iterator<User> friendIterator() throws UserHasNoFriendsException;
    
    /**
     * Creates a new iterator of posts made by this user.
     *
     * @return An iterator of posts
     * @throws UserHasNoPostsException if the user has no posts
     */
    Iterator<Post> postsIterator() throws UserHasNoPostsException;
    
    /**
     * Getter method for the post with the given ID made by this user.
     *
     * @param postID The post ID
     * @return A post object
     */
    Post getPost(int postID) throws PostDoesNotExistException;

    /**
     * Method that allows the user to make a post.
     *
     * @param post The post object
     */
    void post(Post post);

    /**
     * Method that allows the user to receive a post made by one of his/hers friends in the feed.
     *
     * @param post The received post object
     */
    void receivePost(Post post);

    /**
     * Getter method for the post with the given ID received by this user.
     *
     * @param postID The post ID
     * @return A post object representing the received post with given ID
     */
    Post getReceivedPost(int postID);

    /**
     * Method that allows the user to make a comment.
     *
     * @param hashtags of the comment
     * @param comment The comment object
     */
    void comment(List<String> hashtags, Comment comment);
    
    /**
     * Creates a new iterator of comments related to this user on the given topic.
     *
     * @param topic The topic ID
     * @return An iterator of comments
     * @throws NoCommentsException if there are no comments on that topic
     */
    Iterator<Comment> commentIterator(String topic) throws NoCommentsException;

}
